# Generated by Django 5.1.4 on 2024-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_user_selected_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
