# Generated by Django 5.1.4 on 2024-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_user_selected_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='selected_color',
            field=models.CharField(blank=True, default='#6c757d', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='selected_icon',
            field=models.CharField(blank=True, default='fa fa-cat', max_length=50, null=True),
        ),
    ]
