# Generated by Django 5.1.4 on 2024-12-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('marker_color', models.CharField(default='blue', max_length=20)),
            ],
        ),
    ]
