# Generated by Django 5.1.4 on 2024-12-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_markersubcategory_emoji_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('route_type', models.CharField(blank=True, choices=[('walking', 'Walking'), ('cycling', 'Cycling'), ('driving', 'Driving')], max_length=20, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('elevation_gain', models.FloatField(blank=True, null=True)),
                ('isPlan', models.BooleanField(default=True)),
                ('isDraft', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='diary.route'),
        ),
    ]
