# Generated by Django 5.1.4 on 2024-12-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_markersubcategory_emoji_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='is_visited',
            new_name='isDone',
        ),
    ]
