# Generated by Django 5.1.4 on 2024-12-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_rename_is_visited_place_isdone'),
        ('diary', '0010_route_place_route'),
    ]

    operations = [
    ]
