# Generated by Django 5.1.4 on 2024-12-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_merge_20241219_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='datetime',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='isDone',
            new_name='isVisited',
        ),
        migrations.AddField(
            model_name='route',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='isDraft',
            field=models.BooleanField(default=False),
        ),
    ]
