# Generated by Django 5.1.4 on 2024-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_place_cost_place_countryiso_alter_place_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
