# Generated by Django 5.1.4 on 2024-12-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_alter_place_options_place_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
