# Generated by Django 5.1.4 on 2024-12-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_place_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
