# Generated by Django 5.1.4 on 2024-12-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_remove_place_altitude_remove_route_elevation_gain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_type',
        ),
    ]
