# Generated by Django 5.1.4 on 2024-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_rename_cost_place_price_rename_cost_route_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
