# Generated by Django 5.1.4 on 2024-12-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0019_alter_place_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
