# Generated by Django 5.1.4 on 2024-12-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0021_alter_route_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='waypoints',
            field=models.JSONField(default=list),
        ),
    ]
