# Generated by Django 5.1.4 on 2024-12-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0022_route_waypoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
