# Generated by Django 5.1.4 on 2024-12-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0023_alter_route_difficulty_alter_route_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['route_id', 'order']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='waypoints',
        ),
    ]
