# Generated by Django 5.1.4 on 2024-12-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0025_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
