# Generated by Django 5.1.4 on 2024-12-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0027_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bookmarks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
